### ISSUE TITLE
Health indicator

### ISSUE THREAD

**Issue by GreenRover** [SolaceProducts/solace-java-spring-boot#41]
Spring comes with an integrated health indicator.
Here you can see the out of the box list:

https://github.com/joansmith2/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java#L30-L45

Those help for example in an kubernetes/OpenShift context to restart the pod if the broker connections was lost / the session was destroyed).To enshure that the pod is not running without jcsmp session and any possibility to recover this at some point.

Her is the it is a sample health check for JMS:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/jms/JmsHealthIndicator.java

Would you also provide an HelthIndicator for jcsmp?

**Comment by GreenRover** [comment]
Ping @dabgmx @uherbstsolace

**Comment by mackenza** [comment]
thank you for the suggestion @GreenRover . I am with the Product Management team at Solace and we have logged this as an Enhancement Request against this project. I am not able to give a timeframe for which Solace might address the ER.

**Comment by GreenRover** [comment]
A sample how  i would implement it.

```
@Service
@RequiredArgsConstructor
public class SolaceMom implements HealthIndicator {
	private final static String HEALTH_KEY = "Solace";
	
	private JCSMPSession session;
	private final SpringJCSMPFactory factory;
	private boolean connected = false;

	@PostConstruct
	private void init() throws JCSMPException, UnknownHostException {
		session = factory.createSession(null, this::handleSessionEvents);

		producer = session.getMessageProducer(new JCSMPStreamingPublishEventHandler() {

			@Override
			public void handleError(final String messageID, final JCSMPException e, final long timestamp) {
				log.error(String.format("Producer received error for msg: %s@%s - %s", messageID, timestamp, e));
			}

			@Override
			public void responseReceived(final String messageID) {
			}
		});

		connected = true;
	}
	
	private void handleSessionEvents(SessionEventArgs ev) {
		switch (ev.getEvent()) {
		case DOWN_ERROR:
			connected = false;
			log.error("Solace session is going down", ev.getException());
			break;
		case RECONNECTED:
			connected = true;
			log.info("Succesfull reconnected to broker");
			break;
		case RECONNECTING:
			connected = false;
			log.info("Try to reconnected to broker");
			break;
		case SUBSCRIPTION_ERROR:
		case UNKNOWN_TRANSACTED_SESSION_NAME:
		case VIRTUAL_ROUTER_NAME_CHANGED:
		default:
			log.error("Solace: " + ev.getEvent().toString(), ev.getException());
			break;
		}
	}

	@Override
	public Health health() {
        if (!connected) {
            return Health.down().withDetail(HEALTH_KEY, "Not connected").build();
        }
        
        return Health.up().withDetail(HEALTH_KEY, "Connected").build();
	}
}
```

**Comment by GreenRover** [comment]
With spring cloud stream connfigurations like:

```
         binders:
           test_solace:
             type: solace
             environment:
               solace:
                 java:
                   connectRetries: 2
                   reconnectRetries: 4
                   connectRetriesPerHost: 2
                   reconnectRetryWaitInMillis: 500
```

In case of a longer interuption to the broker this well lead into a total app is non functional but not into the expected an app restart.

```
2020-09-07 11:17:51.150  INFO 15896 --- [1_ReactorThread] c.s.j.protocol.impl.TcpClientChannel     : (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: 59313   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - handleException(): Channel Closed Event (smfclient 1)
2020-09-07 11:17:51.150  INFO 15896 --- [ask-scheduler-5] c.s.j.protocol.impl.TcpClientChannel     : (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: 59313   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - handleException(): Channel Closed Event (smfclient 1)
2020-09-07 11:17:51.157  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connecting to host 'orig=shared-rcssolace-node01.otc-test.sbb.ch, host=shared-rcssolace-node01.otc-test.sbb.ch' (host 1 of 2, smfclient 1, attempt 1 of 8, this_host_attempt: 1 of 3)
2020-09-07 11:17:52.418  INFO 15896 --- [1_ReactorThread] c.s.j.i.timers.PubRetransmitTimedTask    : Executing timed publisher retransmission.
.......
2020-09-07 11:25:42.155  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connection attempt failed to host 'shared-rcssolace-node02.otc-test.sbb.ch' ReconnectException com.solacesystems.jcsmp.JCSMPTransportException: (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - Error communicating with the router. cause: java.net.ConnectException: Connection timed out: no further information
2020-09-07 11:25:42.656  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connecting to host 'orig=shared-rcssolace-node02.otc-test.sbb.ch, host=shared-rcssolace-node02.otc-test.sbb.ch' (host 2 of 2, smfclient 1, attempt 8 of 8, this_host_attempt: 2 of 3)
2020-09-07 11:26:03.661  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connection attempt failed to host 'shared-rcssolace-node02.otc-test.sbb.ch' ReconnectException com.solacesystems.jcsmp.JCSMPTransportException: (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - Error communicating with the router. cause: java.net.ConnectException: Connection timed out: no further information
2020-09-07 11:26:04.162  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connecting to host 'orig=shared-rcssolace-node02.otc-test.sbb.ch, host=shared-rcssolace-node02.otc-test.sbb.ch' (host 2 of 2, smfclient 1, attempt 8 of 8, this_host_attempt: 3 of 3)
2020-09-07 11:26:25.196  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Connection attempt failed to host 'shared-rcssolace-node02.otc-test.sbb.ch' ReconnectException com.solacesystems.jcsmp.JCSMPTransportException: (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - Error communicating with the router. cause: java.net.ConnectException: Connection timed out: no further information
2020-09-07 11:26:25.697  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Stale reconnect task, aborting reconnect.
2020-09-07 11:26:25.698  INFO 15896 --- [connect_service] c.s.j.protocol.impl.TcpClientChannel     : Channel Closed (smfclient 1)
2020-09-07 11:26:25.699  INFO 15896 --- [ransmit_service] c.s.j.protocol.impl.TcpClientChannel     : (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - handleException(): Channel Closed Event (smfclient 1)
2020-09-07 11:26:25.705  INFO 15896 --- [connect_service] c.s.jcsmp.impl.flow.SubFlowManagerImpl   : SubChannel (smfclient 1, name=K44279/15896/#00100001/mVVmNoxxjl, desc=) threw exception, non-recoverable. 

com.solacesystems.jcsmp.JCSMPTransportException: (JCSMPTransportException) Error receiving data from underlying connection.
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel$ClientChannelReconnect.call(TcpClientChannel.java:2325) ~[sol-jcsmp-10.9.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: com.solacesystems.jcsmp.JCSMPTransportException: (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - Error communicating with the router.
	at com.solacesystems.jcsmp.protocol.impl.TcpChannel.executePostOnce(TcpChannel.java:251) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.ChannelOpStrategyClient.performOpen(ChannelOpStrategyClient.java:91) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.performOpenSingle(TcpClientChannel.java:399) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.access$800(TcpClientChannel.java:106) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel$ClientChannelReconnect.call(TcpClientChannel.java:2161) ~[sol-jcsmp-10.9.0.jar:na]
	... 4 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_162]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_162]
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111) ~[na:1.8.0_162]
	at com.solacesystems.jcsmp.protocol.smf.SimpleSmfClient.open(SimpleSmfClient.java:887) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.smf.ZSmfClient.open(ZSmfClient.java:62) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.smf.ZSmfClient.doPostNoResponse(ZSmfClient.java:83) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.smf.SimpleSmfClient.doPost(SimpleSmfClient.java:229) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpChannel.executePostOnce(TcpChannel.java:196) ~[sol-jcsmp-10.9.0.jar:na]
	... 8 common frames omitted

2020-09-07 11:26:25.705  INFO 15896 --- [connect_service] c.s.jcsmp.impl.JCSMPXMLMessageProducer   : [JCSMPSession[default@shared-rcssolace-node01.otc-test.sbb.ch,shared-rcssolace-node02.otc-test.sbb.ch] (0001)] Transport exception occurred when message Id is not available

com.solacesystems.jcsmp.JCSMPTransportException: (JCSMPTransportException) Error receiving data from underlying connection.
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel$ClientChannelReconnect.call(TcpClientChannel.java:2325) ~[sol-jcsmp-10.9.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: com.solacesystems.jcsmp.JCSMPTransportException: (Client name: K44279/15896/#00100001/mVVmNoxxjl   Local port: -1   Remote addr: shared-rcssolace-node02.otc-test.sbb.ch  Remote port: 55003) - Error communicating with the router.
	at com.solacesystems.jcsmp.protocol.impl.TcpChannel.executePostOnce(TcpChannel.java:251) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.ChannelOpStrategyClient.performOpen(ChannelOpStrategyClient.java:91) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.performOpenSingle(TcpClientChannel.java:399) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.access$800(TcpClientChannel.java:106) ~[sol-jcsmp-10.9.0.jar:na]
	at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel$ClientChannelReconnect.call(TcpClientChannel.java:2161) ~[sol-jcsmp-10.9.0.jar:na]
	... 4 common frames omitted
```

**Comment by mackenza** [comment]
Our maintainers would certainly entertain a pull request for this if you were interested.

**Comment by GreenRover** [comment]
We add this now to spring cloud stream binder;
